### ISSUE TITLE
Bug: finalize address dict method

### ISSUE THREAD

**Issue by u3716280** [kittiu/thai_tax#17]
Amphur variable wrong place in the Thambol variable

**Comment by kittiu** [comment]
ยังไงนะครับ มีรูปไหม

**Comment by u3716280** [comment]
บรรทัด ที่ 77

**Comment by u3716280** [comment]
แขวง ตัองเป็น ตัวแปร vThambol แต่พี่ใส่ เป็น vAmphur ครับ

**Comment by kittiu** [comment]
รบกวนแปะโค้ดมาหน่อยได้ไหมไม่แน่ใจว่าพูดถึงไฟล์ไหน

**Comment by u3716280** [comment]
![image](https://github.com/kittiu/thai_tax/assets/71708183/9814d326-6303-47c6-a6c3-5ae23f347b2e)

อยู่ใน thai_tax/utils.py ครับ เป็น method def finalize_address_dict(data):

**Comment by kittiu** [comment]
OK แก้แล้วนะครับ ขอบคุณครับที่แจ้ง
