### ISSUE TITLE
Clear Undue Tax Button not hide after clear undue tax

### ISSUE THREAD

**Issue by darkmanst** [kittiu/thai_tax#19]
Clear Undue Tax Button not hide after clear undue tax.

Purchase Order -> Purchase Invoice(Undue Tax) -> Payment (Has Purchase Tax Invoice uncheck)
เมื่อมีการ กด clear undue tax button, และสร้าง New Journal Entry  เรียบร้อยแล้ว (มีการสรา้ง Purchase Tax Invoice เรียบร้อยอัติโนมัติ)

เมื่อกลับเข้ามาหน้า Payment อีกรอบ ปุ่ม Clear Undue Tax  ยังคงอยู่ ทำให้ไม่สามารถแยกออกได้ว่า รายการไหน Clear undue ไปแล้วบ้าง
เมื่อกด ก็ยังสามารถสร้าง Journal Entry  ซ้ำได้อีก

**Comment by darkmanst** [comment]
หรือแบบตอนสร้าง Payment ที่มีการ ติ๊ก Has Purchase Tax Invoice ก็ยังคงมี ปุ่ม Clear Undue ขึ้นอยู่
![screenshot-20240727-120109](https://github.com/user-attachments/assets/d2c02a6d-143e-46fd-9a8e-2ff09a06d801)

**Comment by kittiu** [comment]
Thanks for reporting krub. Fixed with this PR. Also, I made some improvement about WHT creation. Please help test it.

https://github.com/kittiu/thai_tax/pull/20

**Comment by darkmanst** [comment]
Clear Undue Tax Button is now hidden when tax is cleared
Thank you.
