### ISSUE TITLE
Wrong Method Calling 

### ISSUE THREAD

**Issue by darkmanst** [kittiu/thai_tax#23]
Should it be **thai_tax.custom.payment_entry.make_withholding_tax_cert** ?
https://github.com/kittiu/thai_tax/blob/abff2879bc08702baf8284d82d2dc5224ee8af69/thai_tax/public/js/payment_entry.js#L227

**Comment by kittiu** [comment]
https://github.com/kittiu/thai_tax/commit/c00a3bc00c56aa80e91be971c7616683183ffc1c

**Comment by darkmanst** [comment]
Fixed.
https://github.com/kittiu/thai_tax/commit/c00a3bc00c56aa80e91be971c7616683183ffc1c
